apiVersion: v2
name: houndr
description: A fast, trigram-based code search engine for Git repositories - Hound, rewritten in Rust.
type: application
version: "1.1.0"
appVersion: "latest"
keywords:
  - code-search
  - search-engine
  - developer-tools
maintainers:
  - name: André Nogueira
    url: https://github.com/aanogueira
sources:
  - https://github.com/techquestsdev/houndr
home: https://github.com/techquestsdev/houndr
icon: https://raw.githubusercontent.com/techquestsdev/houndr/refs/heads/main/deploy/helm/houndr/icon.svg
annotations:
  artifacthub.io/license: GPL-3.0
  artifacthub.io/category: developer-tools
